name: todorenest
description: Todos app example

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.9.0  <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  intl:
  intl_translation:
  provider: 4.3.2
  flutter_bloc: 6.0.1
  equatable: 1.2.3

  moor: 3.3.1
  sqlite3_flutter_libs: 0.2.0
  path_provider: 1.6.11
  path: 1.7.0

  cupertino_icons: ^0.1.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  moor_generator: 3.3.1
  build_runner: 1.10.0

flutter:
  uses-material-design: true

dependency_overrides:
  analyzer: '0.39.14'